//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.SongPlays = new HashSet<SongPlay>();
            this.Accounts1 = new HashSet<Account>();
            this.Accounts = new HashSet<Account>();
            this.OnSnapAlbums = new HashSet<OnSnapAlbum>();
            this.Playlists = new HashSet<Playlist>();
            this.Songs = new HashSet<Song>();
        }
    
        public int LoginId { get; set; }
        public string Username { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> Room_Id { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Room Room1 { get; set; }
        public virtual ICollection<SongPlay> SongPlays { get; set; }
        public virtual ICollection<Account> Accounts1 { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<OnSnapAlbum> OnSnapAlbums { get; set; }
        public virtual ICollection<Playlist> Playlists { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}
