//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.SongPlays = new HashSet<SongPlay>();
            this.Following = new HashSet<Account>();
            this.Followers = new HashSet<Account>();
            this.Playlists = new HashSet<Playlist>();
            this.Songs = new HashSet<Song>();
        }
    
        public int AccountId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string ProfilePicURL { get; set; }
    
        public virtual ICollection<SongPlay> SongPlays { get; set; }
        public virtual ICollection<Account> Following { get; set; }
        public virtual ICollection<Account> Followers { get; set; }
        public virtual ICollection<Playlist> Playlists { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}
