//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onSnap : DbContext
    {
        public onSnap()
            : base("name=onSnap")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<OnSnapAlbum> OnSnapAlbums { get; set; }
        public virtual DbSet<OnSnapImage> OnSnapImages { get; set; }
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<SongPlay> SongPlays { get; set; }
        public virtual DbSet<Song> Songs { get; set; }
    }
}
