//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnSnapImage
    {
        public OnSnapImage()
        {
            this.OnSnapAlbums = new HashSet<OnSnapAlbum>();
        }
    
        public int Id { get; set; }
        public string ImageDirectory { get; set; }
        public string ImageDescription { get; set; }
    
        public virtual ICollection<OnSnapAlbum> OnSnapAlbums { get; set; }
    }
}
