//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnSnapAlbum
    {
        public OnSnapAlbum()
        {
            this.Accounts = new HashSet<Account>();
            this.OnSnapImages = new HashSet<OnSnapImage>();
        }
    
        public int Id { get; set; }
        public string AlbumName { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<OnSnapImage> OnSnapImages { get; set; }
    }
}
