//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public Song()
        {
            this.SongPlays = new HashSet<SongPlay>();
            this.Accounts = new HashSet<Account>();
            this.Playlists = new HashSet<Playlist>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Length { get; set; }
        public string FilePath { get; set; }
        public string Artist { get; set; }
        public string Genre { get; set; }
        public string Album { get; set; }
        public int Likes { get; set; }
        public bool isAdded { get; set; }
        public Nullable<int> Room_Id { get; set; }
        public int NumberOfPlays { get; set; }
        public string ArtworkURL { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual ICollection<SongPlay> SongPlays { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
